# RAW DATA FROM OLD TRAINER
OLD_Q = [
# ===== bill =====
{"id":"b01","cat":"bill","d":2,"q":"Компания хочет, чтобы у неё был назначенный сотрудник AWS, который знает её архитектуру, проактивно консультирует и координирует эскалации. Какой минимальный план поддержки это даёт?",
 "opts":["Business","Enterprise On-Ramp","Enterprise","Developer"],"a":[2],
 "ex":"Выделенный <b>Technical Account Manager (TAM)</b> есть только в <b>Enterprise</b>. В Enterprise On-Ramp есть пул TAM-ов, но не назначенный персонально. Business даёт только Cloud Support Engineers по кейсам."},
{"id":"b02","cat":"bill","d":2,"q":"Стартап на плане Basic Support получил ошибку при запуске EC2. Откуда он МОЖЕТ получить помощь без апгрейда плана? (Выберите ДВА)",
 "opts":["Открыть технический кейс в AWS Support","AWS re:Post / форумы и документация","Позвонить в AWS Support по телефону","AWS Trusted Advisor (базовые проверки)","Запросить Infrastructure Event Management"],"a":[1,3],
 "ex":"Basic не даёт технических кейсов и телефона — только account/billing кейсы. Доступны бесплатные ресурсы: документация, whitepapers, re:Post, AWS Health Dashboard и <b>7 базовых проверок Trusted Advisor</b>."},
{"id":"b03","cat":"bill","d":1,"q":"Финансовый директор просит показать графики расходов за последние 6 месяцев с разбивкой по сервисам и прогнозом на следующий квартал. Какой сервис?",
 "opts":["AWS Budgets","AWS Cost Explorer","AWS Cost and Usage Report","AWS Pricing Calculator"],"a":[1],
 "ex":"<b>Cost Explorer</b> — визуализация и прогноз (forecast) на 12 месяцев. Budgets — пороги и алерты; CUR — сырые данные в S3; Pricing Calculator — оценка ДО развёртывания."},
{"id":"b04","cat":"bill","d":2,"trap":True,"q":"Нужно, чтобы AWS автоматически определял необычные всплески расходов с помощью ML и присылал уведомления, без ручной настройки порогов. Какой сервис?",
 "opts":["AWS Cost Explorer","AWS Budgets","AWS Cost Anomaly Detection","AWS Trusted Advisor"],"a":[2],
 "ex":"Ключевое слово <b>ML + аномалии</b> = Cost Anomaly Detection. Budgets требует задать пороги вручную. Cost Explorer только визуализирует."},
{"id":"b05","cat":"bill","d":2,"q":"Холдинг с 40 AWS-аккаунтами хочет получать один счёт, автоматически объединять объёмные скидки и запрещать отдельным аккаунтам использовать регионы за пределами ЕС. Какой сервис решает ОБЕ задачи?",
 "opts":["AWS Control Tower","AWS Organizations","AWS IAM Identity Center","AWS Billing Conductor"],"a":[1],
 "ex":"<b>Organizations</b> = consolidated billing (один счёт, объединённые volume discounts, шаринг RI/Savings Plans) + <b>SCP</b> для ограничений. Control Tower построен поверх Organizations, но сам по себе ответ на «биллинг + политики» — Organizations."},
{"id":"b06","cat":"bill","d":3,"q":"Компания купила Reserved Instances в аккаунте A внутри Organization. Аккаунт B запустил такие же инстансы. Что произойдёт по умолчанию?",
 "opts":["Скидка RI применится только к аккаунту A","Скидка RI может примениться к аккаунту B благодаря RI sharing в consolidated billing","Аккаунт B должен купить свои RI","RI нельзя использовать в Organizations"],"a":[1],
 "ex":"В consolidated billing скидки RI и Savings Plans <b>по умолчанию расшариваются</b> между аккаунтами организации (можно отключить). Это частый вопрос на уровне SAA."},
{"id":"b07","cat":"bill","d":2,"q":"Команда хочет получать письмо, когда прогнозируемые (forecasted) расходы за месяц превысят $5 000, а не когда они уже потрачены. Какой инструмент?",
 "opts":["AWS Cost Explorer","AWS Budgets","AWS Cost Anomaly Detection","Amazon CloudWatch billing alarm"],"a":[1],
 "ex":"<b>Budgets</b> поддерживает алерты и по фактическим, и по <b>прогнозируемым</b> значениям. CloudWatch billing alarm срабатывает только на фактические расходы."},
{"id":"b08","cat":"bill","d":2,"q":"Какие два способа снизить стоимость EC2 для стабильной нагрузки на 3 года дают наибольшую скидку? (Выберите ДВА)",
 "opts":["On-Demand","Spot Instances","Reserved Instances (All Upfront, 3 года)","Compute Savings Plans (3 года)","Dedicated Hosts On-Demand"],"a":[2,3],
 "ex":"Для <b>стабильной</b> нагрузки — RI или Savings Plans (до ~72%). Spot дешевле (до 90%), но может быть прерван — не для стабильной нагрузки."},
{"id":"b09","cat":"bill","d":3,"q":"Что из перечисленного НЕ входит в бесплатный (Basic) набор, но доступно всем аккаунтам без платы?",
 "opts":["Полный набор проверок Trusted Advisor","AWS Personal Health Dashboard","Кейсы к Cloud Support Engineers","Response time < 1 час для production-down"],"a":[1],
 "ex":"<b>AWS Health Dashboard</b> (персонализированный) доступен всем. Полный Trusted Advisor — с Business. Тех. кейсы — с Developer. < 1 часа для production-down — с Business."},
{"id":"b10","cat":"bill","d":2,"q":"Компания хочет оценить стоимость будущей архитектуры (10 EC2, RDS, S3) ДО того, как что-то развернуть. Какой инструмент?",
 "opts":["AWS Cost Explorer","AWS Pricing Calculator","AWS Budgets","AWS Cost and Usage Report"],"a":[1],
 "ex":"<b>Pricing Calculator</b> — оценка ДО развёртывания. Cost Explorer работает с уже понесёнными затратами."},
{"id":"b11","cat":"bill","d":2,"q":"Что из перечисленного является платным в AWS? (Выберите ДВА)",
 "opts":["Входящий трафик из интернета в EC2","Исходящий трафик из EC2 в интернет","Трафик между AZ внутри региона","Трафик из EC2 в S3 в том же регионе через Gateway Endpoint","Использование IAM"],"a":[1,2],
 "ex":"Ингресс бесплатный, <b>egress платный</b>, трафик <b>между AZ</b> платный (частая ловушка). S3 в том же регионе через Gateway Endpoint — бесплатно. IAM бесплатен."},
{"id":"b12","cat":"bill","d":2,"q":"Что верно об AWS Free Tier? (Выберите ДВА)",
 "opts":["Всё бесплатно первые 12 месяцев","Есть три типа: 12 месяцев бесплатно, Always Free, Trials","Lambda даёт 1 млн запросов в месяц бесплатно всегда (Always Free)","Free Tier действует только для EC2","После 12 месяцев аккаунт блокируется"],"a":[1,2],
 "ex":"Три типа Free Tier. Lambda (1M запросов), DynamoDB (25 ГБ), SNS/SQS — <b>Always Free</b>. EC2 t2/t3.micro 750 ч — 12 месяцев."},
{"id":"b13","cat":"bill","d":3,"q":"Финансы хотят видеть в счёте расходы в разрезе проектов и отделов. Что нужно сделать?",
 "opts":["Создать отдельный аккаунт на каждый проект","Активировать cost allocation tags и тегировать ресурсы","Включить AWS Cost Anomaly Detection","Купить Savings Plans на каждый отдел"],"a":[1],
 "ex":"<b>Cost allocation tags</b> (user-defined + AWS-generated) нужно <b>активировать</b> в Billing console — тогда они появятся в Cost Explorer и CUR."},
{"id":"b14","cat":"bill","d":2,"q":"Чем Compute Savings Plans отличаются от Standard Reserved Instances? (Выберите ДВА)",
 "opts":["Savings Plans привязаны к конкретному типу инстанса и региону","Compute Savings Plans применяются к EC2, Fargate и Lambda в любом регионе","RI дают большую гибкость, чем Savings Plans","Savings Plans — обязательство в $/час на 1 или 3 года","Savings Plans нельзя расшарить в Organizations"],"a:[1,3],
 "ex":"Savings Plans = обязательство тратить $/час, гибче RI (семейство, регион, Fargate/Lambda). Standard RI привязаны к типу/региону, но их можно продать на RI Marketplace."},
{"id":"b15","cat":"bill","d":2,"q":"Клиент на плане Business хочет получить помощь в планировании крупного запуска (Infrastructure Event Management). Что верно?",
 "opts":["IEM включён в Business бесплатно","IEM доступен в Business за дополнительную плату, в Enterprise — включён","IEM доступен только в Enterprise","IEM доступен на всех планах"],"a":[1],
 "ex":"<b>IEM</b>: Enterprise — включён, Business — за доплату."},
{"id":"b16","cat":"bill","d":3,"q":"Какой инструмент даёт детализированные (почасовые, по ресурсам) данные о затратах в формате CSV/Parquet в S3 для загрузки в BI-систему?",
 "opts":["AWS Cost Explorer","AWS Cost and Usage Report (CUR)","AWS Budgets","AWS Billing Conductor"],"a":[1],
 "ex":"<b>CUR</b> — самый детальный источник, выгружается в S3, анализ через Athena/QuickSight."},
{"id":"b17","cat":"bill","d":2,"q":"Что влияет на стоимость EC2 On-Demand? (Выберите ДВА)",
 "opts":["Тип инстанса и регион","Количество IAM-пользователей","Объём входящего трафика","Операционная система (Linux vs Windows)","Число Security Groups"],"a:[0,3],
 "ex":"Цена EC2 зависит от типа, региона, ОС/лицензии, tenancy. Ингресс бесплатен; IAM и SG бесплатны."},
{"id":"b18","cat":"bill","d":3,"q":"Разработчик хочет автоматизировать создание support-кейсов из своего скрипта через AWS Support API. Какой минимальный план?",
 "opts":["Basic","Developer","Business","Enterprise"],"a":[2],
 "ex":"<b>AWS Support API</b> — с плана Business."},
{"id":"b19","cat":"bill","d":2,"q":"Компания хочет получить кредиты и пройти технический аудит для запуска SaaS-продукта, а также включиться в программу партнёров. Куда обратиться?",
 "opts":["AWS Marketplace","AWS Partner Network (APN)","AWS Activate","AWS Professional Services"],"a":[1],
 "ex":"<b>APN</b> — партнёрская программа (Consulting/Technology partners). Activate — кредиты для стартапов."}
]

print(f"Loaded {len(OLD_Q)} billing questions.")
